### ISSUE TITLE
Changing API to {:ok, }, {:error, }

### ISSUE THREAD

**Issue by jonzlin95** [stephenmoloney/fastimage#7]
Hi man, firstly thanks for your work! I've been using FastImage in one of my apps in production.

Just curious about your thoughts on changing the API to more inline with other similar Elixir behavior. 

```
FastImage.size() -> {:ok, %{width: _, height: _}} 

FastImage.size!() -> {%width: _, height: _}}
```

Definitely down to send in a PR with this change. Cheers.

**Comment by stephenmoloney** [comment]
Hi @jonzlin95,
Thanks for your complement. 

I was cognizant of this deviation from the norm early on, I just ran out of time to make that change. I've been away from elixir for quite some time due to other commitments but I am back using elixir from tomorrow so good timing! 

I'd like to see a PR for this change! 😃 

P.S.
If you want to create a struct for `width and height` map that's ok too.... not sure if its needed though for such a simple data structure though.

**Comment by stephenmoloney** [comment]
On further though, perhaps this is not necessary - [example](https://hexdocs.pm/plug/Plug.Conn.html#fetch_query_params/2)
